# Generated by Django 3.2.6 on 2021-08-12 14:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atributes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': '1. Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_slide', models.ImageField(upload_to='images/slides', verbose_name='URL image ')),
                ('actif', models.BooleanField(default=False, verbose_name='Active')),
                ('is_big', models.BooleanField(default=False, verbose_name='Grande photo (1920 x 570)')),
                ('is_small', models.BooleanField(default=False, verbose_name='Medium photo (720 x 540)')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Sous Catégorie',
                'verbose_name_plural': '2. Sous Catégorie',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Déscription')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ancien prix')),
                ('volume', models.IntegerField(blank=True, verbose_name='Contenance')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
                ('new', models.BooleanField(default=True, verbose_name='Nouveau')),
                ('top', models.BooleanField(default=True, verbose_name='Meilleur vente')),
                ('status', models.CharField(blank=True, choices=[('N', 'Nouveau'), ('R', 'Rupture'), ('P', 'Promotion')], default='N', max_length=1, null=True, verbose_name='Status')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo7', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo8', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo9', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('photo10', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
                ('cheveux', models.ManyToManyField(blank=True, to='atributes.Cheveux')),
                ('gamme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.gamme')),
                ('sous_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.subcategory', verbose_name='Sous Catégorie')),
                ('tag', models.ManyToManyField(blank=True, to='atributes.Tag')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': '3. Produits',
                'ordering': ('id',),
            },
        ),
    ]
