# Generated by Django 3.2.6 on 2021-08-15 10:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ('id',), 'verbose_name': 'Formulaire de contact', 'verbose_name_plural': 'Formulaire de contact'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ('id',), 'verbose_name': 'Photos du site'},
        ),
        migrations.AddField(
            model_name='product',
            name='utilisation',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name="Conseils d'utilisation "),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Déscription du produit'),
        ),
    ]
