# Generated by Django 3.2.6 on 2021-08-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210815_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
