# Generated by Django 3.2.6 on 2021-08-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atributes', '0002_parfum'),
        ('core', '0006_auto_20210816_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo9',
        ),
        migrations.AddField(
            model_name='product',
            name='parfum',
            field=models.ManyToManyField(blank=True, to='atributes.Parfum'),
        ),
        migrations.CreateModel(
            name='PhotoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/produits')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.product')),
            ],
        ),
    ]
