# Generated by Django 3.2.6 on 2021-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210818_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduct',
            name='photo',
            field=models.ImageField(upload_to='images/produits'),
        ),
    ]
