# Generated by Django 3.2.6 on 2021-08-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_photoproduct_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoproduct',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.product'),
        ),
    ]
