# Generated by Django 3.2.6 on 2021-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(upload_to='images/logos', verbose_name='Logo')),
                ('logo_negatif', models.ImageField(upload_to='images/slides', verbose_name='Logo négatif')),
                ('home_banner', models.ImageField(upload_to='images/banners', verbose_name='Slider acceuil (1200 x 500)')),
                ('larg_banner', models.ImageField(upload_to='images/logos', verbose_name="Banner page d'accueil (1400 x 370)")),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titre')),
                ('adress', models.CharField(blank=True, max_length=50, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name="email de l'entreprise")),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name="numéro de téléphone de l'entreprise")),
            ],
            options={
                'verbose_name': 'Infomations',
                'ordering': ('id',),
            },
        ),
    ]
