# Generated by Django 3.2.6 on 2021-08-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210819_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '3. Banner'},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '1. Infomations'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '2. Grande Photo'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='home_banner',
        ),
        migrations.RemoveField(
            model_name='business',
            name='larg_banner',
        ),
    ]
