# Generated by Django 3.2.6 on 2021-08-22 09:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20210819_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text a propos'),
        ),
    ]
