# Generated by Django 3.2.6 on 2021-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Facebook'),
        ),
        migrations.AddField(
            model_name='business',
            name='insta',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Lien page Instagram'),
        ),
    ]
